events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        # 1. UI
        location / {
            root   /usr/share/nginx/html;
            index  index.html;
        }

        # 2. MANAGER API (For Agents)
        location /wazuh-api/ {
            rewrite ^/wazuh-api/(.*) /$1 break;
            proxy_pass https://wazuh.manager:55000;
            proxy_ssl_verify off;
            proxy_set_header Host $host;
        }

        # 3. INDEXER API (For Real Logs/Alerts) <--- NEW!
        location /indexer-api/ {
            rewrite ^/indexer-api/(.*) /$1 break;
            proxy_pass https://wazuh.indexer:9200;
            proxy_ssl_verify off;
            proxy_set_header Host $host;
            
            # Allow the browser to make these requests
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
        }
    }
}